FROM registry.access.redhat.com/ubi9/python-311:latest

COPY common /app/common
COPY serving /app/serving

WORKDIR /app/

RUN pip install -r common/requirements.txt -r serving/requirements.txt

USER 1001
ENV PYTHONPATH=/app
WORKDIR /app/serving

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]