FROM registry.access.redhat.com/ubi9/python-311:latest as base

COPY common /app/common
COPY training /app/training

WORKDIR /app/

USER root
RUN yum -y install mesa-libGL
RUN pip install -r common/requirements.txt -r training/requirements.txt

USER 1001
ENV PYTHONPATH=/app
WORKDIR /app/training

FROM base AS training

CMD ["python", "app.py"]
