FROM registry.access.redhat.com/ubi9/python-311:latest as base

COPY common /app/common
COPY serving /app/serving

WORKDIR /app/

RUN pip install -r common/requirements.txt -r serving/requirements.txt

USER 1001
ENV PYTHONPATH=/app
WORKDIR /app/serving


FROM base as testing

CMD python -m unittest discover ../common && python -m unittest


FROM base AS serving

CMD ["uvicorn", "app:app", "--workers", "4", "--host", "0.0.0.0", "--port", "8000"]
