apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  namespace: {{ $Release.Namespace }}
spec:
  port:
    targetPort: 8000 
  to:
    kind: Service
    name: {{ .Release.Name }}