apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_name }}
  labels:
    app: {{ cookiecutter.project_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ cookiecutter.project_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_name }}
    spec:
      containers:
      - name: {{ cookiecutter.project_name }}
        image: {{ cookiecutter.project_name }}
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3