apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ cookiecutter.project_name }}
  name: {{ cookiecutter.project_name }}
  namespace: {{ $Release.Namespace }}
spec:
  lookupPolicy:
    local: true