namespace:
  enabled: true
  argocd:
    name: default

replicaCount: 1

image:
  pullPolicy: Always
  registry: ${{values.image_registry}}
  host: ${{values.image_host}}
  organization: ${{values.image_organization}}
  name: ${{values.image_name}}
  # Overrides the image tag whose default is the chart appVersion.

isDev: False

route:
  host: ""
  path: /

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

notebookResources:
  limits:
    cpu: '2'
    memory: 8Gi
  requests:
    cpu: '1'
    memory: 8Gi


nodeSelector: {}

tolerations: []

affinity: {}
