{{ if .Values.isProd }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: ${{ values.image_name }}
  name: ${{ values.image_name }}
  namespace: {{ .Release.Namespace }}
spec: {}
{{ end }}