{{ if .Values.isProd }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Release.Name }}-serving
  name: {{ .Release.Name }}-serving
  namespace: {{ .Release.Namespace }}
spec: {}
{{ end }}