kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-model-controller
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
  - verbs:
      - create
      - delete
    apiGroups:
      - batch
    resources:
      - jobs
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-model-controller
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: model-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-model-controller
