apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-template.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-app
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000