{{- if not .Values.isProd }}
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/last-image-selection: 's2i-generic-data-science-notebook:2024.1'
    notebooks.opendatahub.io/last-size-selection: Small
    opendatahub.io/username: user
    openshift.io/description: "Workbench with code repo present for quick experimentation"
    openshift.io/display-name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    {{- include "backstage.labels" . | nindent 8 }}
    {{- include "ai-template.selectorLabels" . | nindent 8 }}
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
        - name: git-clone
          image: registry.access.redhat.com/ubi9/python-311
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args:
            - -ec
            - |-
              if [ ! -d /opt/app-root/src/code ] || [ -z $( ls -A /opt/app-root/src/code/ ) ]; then git clone {{ cookiecutter.git_repo }} /opt/app-root/src/code; fi
          volumeMounts:
            - name: mytest
              mountPath: /opt/app-root/src
          kind: init
      containers:
      - env:
        - name: PYTHONPATH
          value: /opt/app-root/src/code
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
            --ServerApp.token=''
            --ServerApp.password=''
            --ServerApp.base_url=/notebook/{{ .Release.Name }}/{{ .Release.Name }}
            --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.1
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ .Release.Name }}/{{ .Release.Name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .Release.Name }}
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ .Release.Name }}/{{ .Release.Name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        {{- with .Values.notebookResources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: {{ .Release.Name }}
        workingDir: /opt/app-root/src
      - args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account={{ .Release.Name }}
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"{{ .Release.Name }}","  ":"$(NAMESPACE)"}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:2246f6a2f5d48fb94e9bcf30a4945e4324ddc76ea49140f5483539450ab0b621
        image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.14
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      volumes:
      - name: {{ .Release.Name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-oauth-config
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-tls
{{- end }}